# Create and view interactive cheat sheets for *nix commands
brew "cheat"
# Mac App Store command-line interface
brew "mas"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft OneNote", id: 784801555
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
